name: "List of Files"
description: "List of files in a provided directory"
inputs:
  path:
    description: "Path to directory:"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        find ${{ inputs.path }} -type f > files-list.txt
        echo "output_file_path=$(pwd)/files-list.txt" >> $GITHUB_ENV
      shell: bash
