name: Main Workflow
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Build version'
        required: false
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create list of files in directory
      uses: ./.github/actions
      with:
        path: ./root_dir
    - name: Output file path
      run: echo "File path is $output_file_path"
  
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: $output_file_path
        asset_name: files-list.txt
        asset_content_type: text/plain

    - name: Output Log
      run: |
        ref_name="${{ github.ref_name }}"
        if [ -z "${{ github.event.inputs.version }}" ]; then
          echo "Building latest version for $ref_name"
        else
          echo "Building version ${{ github.event.inputs.version }} for $ref_name"
        fi
