name: Main Workflow
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch or tag to build'
        required: true
        default: 'main'
      version:
        description: 'Build version'
        required: false
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Build
      run: |
        if [ -z "${{ github.event.inputs.version }}" ]; then
          echo "Building latest version for ${{ github.event.inputs.branch }}"
        else
          echo "Building version ${{ github.event.inputs.version }} for ${{ github.event.inputs.branch }}"
        fi