name: Main Workflow
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Build version'
        required: false
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Build
      shell: bash
      run: |
        ref_name="${{ github.ref_name }}"
        echo "$ref_name"
        if [ -z "${{ github.event.inputs.version }}" ]; then
          echo "Building latest version for $ref_name"
        else
          echo "Building version ${{ github.event.inputs.version }} for $ref_name"
        fi